sonar.organization=Esteban Maya
sonar.projectKey=kata-devops

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10,3.11,3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit.xml

sonar.sourceEncoding=UTF-8