[tox]
envlist = py39, py310, py311, py312, lint, type, security, coverage
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=src --cov-config=.coveragerc --cov-report=term-missing tests/

[testenv:lint]
deps =
    ruff
    black
commands =
    ruff check src tests
    black --check src tests

[testenv:type]
deps = mypy
commands = mypy src

[testenv:security]
deps = bandit
commands = bandit -r src -ll

[testenv:coverage]
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=src --cov-config=.coveragerc --cov-report=xml:coverage.xml --cov-report=term-missing --junitxml=xunit.xml tests/